### ISSUE TITLE
RuntimeError: received 0 items of ancdata

### ISSUE THREAD

**Issue by jcohenadad** [jcohenadad/monai-tutorial#1]
<details><summary>Terminal output</summary>

```console
(venv) p101317@rosenberg:~/code/monai-tutorial$ python spleen_segmentation_3d.py 
MONAI version: 1.2.dev2305
Numpy version: 1.24.1
Pytorch version: 1.13.1+cu117
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: a1a168790145c690b3cd96fa90bef1c4a7ef33ff
MONAI __file__: /home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.10
ITK version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 5.0.0
scikit-image version: NOT INSTALLED or UNKNOWN VERSION.
Pillow version: 9.4.0
Tensorboard version: NOT INSTALLED or UNKNOWN VERSION.
gdown version: 4.6.0
TorchVision version: NOT INSTALLED or UNKNOWN VERSION.
tqdm version: 4.64.1
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: NOT INSTALLED or UNKNOWN VERSION.
pandas version: NOT INSTALLED or UNKNOWN VERSION.
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

/home/GRAMES.POLYMTL.CA/p101317/data_nvme_p101317/monai_data
/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/monai/utils/deprecate_utils.py:321: FutureWarning: monai.transforms.io.dictionary LoadImaged.__init__:image_only: Current default value of argument `image_only=False` has been deprecated since version 1.1. It will be changed to `image_only=True` in version 1.3.
  warn_deprecated(argname, msg, warning_category)
image shape: torch.Size([228, 158, 113]), label shape: torch.Size([228, 158, 113])
Loading dataset: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:30<00:00,  1.05it/s]
Loading dataset: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:06<00:00,  1.39it/s]
----------
epoch 1/600
1/16, train_loss: 0.6642
2/16, train_loss: 0.6765
3/16, train_loss: 0.6728
4/16, train_loss: 0.6668
5/16, train_loss: 0.6559
6/16, train_loss: 0.6678
7/16, train_loss: 0.6444
8/16, train_loss: 0.6664
9/16, train_loss: 0.6518
10/16, train_loss: 0.6375
11/16, train_loss: 0.6569
12/16, train_loss: 0.6300
13/16, train_loss: 0.6521
14/16, train_loss: 0.6571
15/16, train_loss: 0.6549
16/16, train_loss: 0.6258
epoch 1 average loss: 0.6551
----------
epoch 2/600
1/16, train_loss: 0.6078
2/16, train_loss: 0.6501
3/16, train_loss: 0.6468
4/16, train_loss: 0.6380
5/16, train_loss: 0.6559
6/16, train_loss: 0.6135
7/16, train_loss: 0.6224
8/16, train_loss: 0.6330
9/16, train_loss: 0.6217
10/16, train_loss: 0.6015
11/16, train_loss: 0.6424
12/16, train_loss: 0.6243
13/16, train_loss: 0.6521
14/16, train_loss: 0.6216
15/16, train_loss: 0.6332
16/16, train_loss: 0.6160
epoch 2 average loss: 0.6300
saved new best metric model
current epoch: 2 current mean dice: 0.0342
best mean dice: 0.0342 at epoch: 2
----------
epoch 3/600
1/16, train_loss: 0.5854
2/16, train_loss: 0.6112
3/16, train_loss: 0.6336
4/16, train_loss: 0.6396
5/16, train_loss: 0.6144
6/16, train_loss: 0.6166
7/16, train_loss: 0.6093
8/16, train_loss: 0.6298
9/16, train_loss: 0.6250
10/16, train_loss: 0.6165
11/16, train_loss: 0.6124
12/16, train_loss: 0.6285
13/16, train_loss: 0.6218
14/16, train_loss: 0.6030
15/16, train_loss: 0.6062
16/16, train_loss: 0.6210
epoch 3 average loss: 0.6171
----------
epoch 4/600
1/16, train_loss: 0.6168
2/16, train_loss: 0.6074
3/16, train_loss: 0.5649
4/16, train_loss: 0.5867
5/16, train_loss: 0.5751
6/16, train_loss: 0.6155
7/16, train_loss: 0.5611
8/16, train_loss: 0.6369
9/16, train_loss: 0.6263
10/16, train_loss: 0.6089
11/16, train_loss: 0.5953
12/16, train_loss: 0.5858
13/16, train_loss: 0.6123
14/16, train_loss: 0.6053
15/16, train_loss: 0.5929
16/16, train_loss: 0.6340
epoch 4 average loss: 0.6016
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/spleen_segmentation_3d.py", line 194, in <module>
    for val_data in val_loader:
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/monai-tutorial/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 164, in recvfds
    raise RuntimeError('received %d items of ancdata' %
RuntimeError: received 0 items of ancdata
```

</details>

Related to:
- https://github.com/Project-MONAI/MONAI/issues/2498
- https://github.com/Project-MONAI/MONAI/issues/701
- https://discuss.pytorch.org/t/runtimeerror-received-0-items-of-ancdata/4999/5

**Comment by jcohenadad** [comment]
✅  SOLVED

reducing num_worker from 4 to 2:

(the first 2 peaks were with num_worker=4):

See MEM from `rosenberg`

![image](https://user-images.githubusercontent.com/2482071/215620583-07c907e7-1e7b-4991-8912-9f36923873bd.png)
